#pragma once

#include <cstdint>
#include <atomic>
#include <iostream>

namespace osm {
/**
 * These statistics are generated by the area assembler code. They
 * tell the user of the assembler a lot about the objects this area
 * is made out of, what happened during the assembly, and what errors
 * there were.
 */
struct area_stats {
  // Thread-safe merge: atomically adds `other` into `*this`. Uses
  // `std::atomic_ref` on each destination field so several threads can call
  // this concurrently without a mutex. The source is read non-atomically and
  // is expected to be a thread-local accumulator (e.g. from a single
  // assembly).
  area_stats& operator+=(const area_stats& other) noexcept {
    auto add = [](std::uint64_t& dst, std::uint64_t const src) {
      std::atomic_ref{dst}.fetch_add(src, std::memory_order_relaxed);
    };
    add(area_really_complex_case, other.area_really_complex_case);
    add(area_simple_case, other.area_simple_case);
    add(area_touching_rings_case, other.area_touching_rings_case);
    add(duplicate_nodes, other.duplicate_nodes);
    add(duplicate_segments, other.duplicate_segments);
    add(duplicate_ways, other.duplicate_ways);
    add(from_relations, other.from_relations);
    add(from_ways, other.from_ways);
    add(inner_rings, other.inner_rings);
    add(inner_with_same_tags, other.inner_with_same_tags);
    add(intersections, other.intersections);
    add(member_ways, other.member_ways);
    add(no_tags_on_relation, other.no_tags_on_relation);
    add(no_way_in_mp_relation, other.no_way_in_mp_relation);
    add(nodes, other.nodes);
    add(open_rings, other.open_rings);
    add(outer_rings, other.outer_rings);
    add(short_ways, other.short_ways);
    add(single_way_in_mp_relation, other.single_way_in_mp_relation);
    add(touching_rings, other.touching_rings);
    add(ways_in_multiple_rings, other.ways_in_multiple_rings);
    add(wrong_role, other.wrong_role);
    add(invalid_locations, other.invalid_locations);
    return *this;
  }

  void print_stats() {
    std::cout << " area_really_complex_case=" << area_really_complex_case
              << " area_simple_case=" << area_simple_case
              << " area_touching_rings_case=" << area_touching_rings_case
              << " duplicate_nodes=" << duplicate_nodes
              << " duplicate_segments=" << duplicate_segments
              << " duplicate_ways=" << duplicate_ways
              << " from_relations=" << from_relations
              << " from_ways=" << from_ways << " inner_rings=" << inner_rings
              << " inner_with_same_tags=" << inner_with_same_tags
              << " intersections=" << intersections
              << " member_ways=" << member_ways
              << " no_tags_on_relation=" << no_tags_on_relation
              << " no_way_in_mp_relation=" << no_way_in_mp_relation
              << " nodes=" << nodes << " open_rings=" << open_rings
              << " outer_rings=" << outer_rings << " short_ways=" << short_ways
              << " single_way_in_mp_relation=" << single_way_in_mp_relation
              << " touching_rings=" << touching_rings
              << " ways_in_multiple_rings=" << ways_in_multiple_rings
              << " wrong_role=" << wrong_role
              << " invalid_locations=" << invalid_locations << std::endl;
  }

  // Most difficult case with rings touching in multiple points
  std::uint64_t area_really_complex_case = 0;
  // Simple case, no touching rings
  std::uint64_t area_simple_case = 0;
  // More difficult case with touching rings
  std::uint64_t area_touching_rings_case = 0;
  // Consecutive identical nodes or consecutive nodes with same location
  std::uint64_t duplicate_nodes = 0;
  // Segments duplicated (going back and forth)
  std::uint64_t duplicate_segments = 0;
  // Ways that are in relation more than once
  std::uint64_t duplicate_ways = 0;
  // Area created from multipolygon relation
  std::uint64_t from_relations = 0;
  // Area created from way
  std::uint64_t from_ways = 0;
  // Number of inner rings
  std::uint64_t inner_rings = 0;
  // Number of inner ways with same tags as area
  std::uint64_t inner_with_same_tags = 0;
  // Number of intersections between segments
  std::uint64_t intersections = 0;
  // Number of ways in the area
  std::uint64_t member_ways = 0;
  // No tags on relation (old-style multipolygon with tags on outer ways)
  std::uint64_t no_tags_on_relation = 0;
  // Multipolygon relation with no way members
  std::uint64_t no_way_in_mp_relation = 0;
  // Number of nodes in the area
  std::uint64_t nodes = 0;
  // Number of open rings in the area
  std::uint64_t open_rings = 0;
  // Number of outer rings in the area
  std::uint64_t outer_rings = 0;
  // Three or more segments with same end points
  std::uint64_t overlapping_segments = 0;
  // Number of ways with less than two nodes
  std::uint64_t short_ways = 0;
  // Multipolygon relation containing a single way
  std::uint64_t single_way_in_mp_relation = 0;
  // Rings touching in a node
  std::uint64_t touching_rings = 0;
  // Different segments of a way ended up in different rings
  std::uint64_t ways_in_multiple_rings = 0;
  // Member has wrong role (not "outer", "inner", or empty)
  std::uint64_t wrong_role = 0;
  // Invalid location found
  std::uint64_t invalid_locations = 0;
};  // struct area_stats

}  // namespace osm
